#!/bin/bash

echo パスワードマネージャーにようこそ!\ 
echo "次の選択肢から入力してください(Add Password/Get Password/Exit)"\ 

read q 

case $q in
	"Add Password")
		echo サービス名を入力してください\                              
	  	read service
		echo ユーザー名を入力してください\ 
		read name
		echo パスワードを入力してください\ 
		read pass
		echo $service:$name:$pass >> keystore.txt 
		echo パスワードの追加は成功しました。
	;;
	"Get Password")

		echo サービス名を入力してください\ 
		read a
		case $a in 
			while read b
			do
				echo"$b"
			done < keystore.txt) 
			echo そのサービスは登録されていません。\ 
			;;	
		
		esac
	;;

	"Exit")
		echo Thank you!
	;;
esac
